<?php

namespace AppBundle\Repository;

/**
 * dostepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dostepRepository extends \Doctrine\ORM\EntityRepository
{
}
