<?php

namespace AppBundle\Repository;

/**
 * kursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class kursRepository extends \Doctrine\ORM\EntityRepository
{
}
