<?php

namespace AppBundle\Repository;

/**
 * plikRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class plikRepository extends \Doctrine\ORM\EntityRepository
{
}
