<?php

namespace AppBundle\Repository;

/**
 * pobieranie_plikuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pobieranie_plikuRepository extends \Doctrine\ORM\EntityRepository
{
}
