<?php

namespace AppBundle\Repository;

use AppBundle\Entity\users;

/**
 * usersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class usersRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return int
     */
    public function countUsers()
    {
        $users = $this->createQueryBuilder('u')
            ->orderBy('u.id', 'asc')
            ->getQuery()
            ->getResult();
        return count($users);
    }

    /**
     * @param $username
     * @return users
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getByUsername($username)
    {
        $qb = $this->createQueryBuilder('u')
            ->where('u.login = :username')
            ->setParameter('username', $username);
        $query = $qb->getQuery();
        $user = $query->getSingleResult();

        return $user;
    }
}
