app:
    resource: '@AppBundle/Controller/'
    type: annotation

appyml:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /

_welcome:
    path: /
    defaults: { _controller: AppBundle:Default:index }

_register:
    path: /register
    defaults: { _controller: AppBundle:Register:index }

_login:
  path: /login
  defaults: { _controller: AppBundle:Login:index }

_main:
  path: /main
  defaults: { _controller: AppBundle:Main:index }
  
_logs:
 path: /logs
 defaults: { _controller: AppBundle:Logs:index }

_settings:
  path: /settings
  defaults: { _controller: AppBundle:Settings:index }